# Generated by Django 4.2 on 2023-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank='false', max_length=255, null='false', unique='true', verbose_name='dni')),
                ('nombre', models.CharField(max_length=255, null='false', verbose_name='nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('ciudad', models.CharField(max_length=255, verbose_name='ciudad')),
                ('direccion', models.CharField(max_length=255, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=255, verbose_name='telefono')),
                ('fechaAlta', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default='true')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
    ]
