# Generated by Django 4.2 on 2023-05-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_tipomascota_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='historiaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha de consulta')),
                ('observaciones', models.CharField(max_length=255, null='false', verbose_name='observaciones')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinaria.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'historia clinica',
                'verbose_name_plural': 'historias clinica',
                'db_table': 'Historia',
                'ordering': ['id'],
            },
        ),
    ]
